[workspace]

members = [
    "rofl_crypto",
    "rofl_service"
]

[patch.crates-io]
tinytemplate = { git = "https://github.com/bheisler/TinyTemplate", branch = "master" }
#curve25519-dalek-ng = { path = "/Users/hidde/Documents/PhD/curve25519-dalek-ng" }

[profile.release]
opt-level = 3
