# Sample configuration file for federated dropout

num_clients: 10
num_selected_clients: 10
num_malicious_clients: 0

num_rounds: 1000
batch_size: 128
num_epochs: 1
optimizer: SGD
learning_rate: 0.00001
model: bhagoji_intrinsic

save_updates: false