# Sample configuration file for federated dropout

num_clients: 3383
num_selected_clients: 30
num_malicious_clients: 113
global_learning_rate: -1

scale_attack: True
scale_attack_weight: 30
num_rounds: 100000
batch_size: 24
num_epochs: 2
optimizer: Adam
learning_rate: 0.001
model_name: bhagoji_intrinsic
save_updates: false
dataset: femnist
data_distribution: nonIID
backdoor_tasks: 30
attack_frequency: 1

attack_type: min_loss
backdoor_attack_objective: [7, 1]
backdoor_stealth: false
estimate_other_updates: false