# Sample configuration file for federated dropout

num_clients: 1
num_selected_clients: 1
num_malicious_clients: 0
global_learning_rate: -1

num_rounds: 100000
batch_size: 24
num_epochs: 1
optimizer: Adam
learning_rate: 0.0001
model_name: bhagoji_intrinsic
save_updates: false
dataset: femnist
data_distribution: nonIID