environment:
  num_clients: 20
  num_selected_clients: 10
  num_malicious_clients: 0
  experiment_name: "backdoor_tasks_noattack"
  use_config_dir: true
server:
  num_rounds: 10
  num_test_batches: 25
  aggregator:
    name: FedAvg
  global_learning_rate: 1.0
client:
  model_name: dev
#  num_params: 274442
  num_params: 19166
  # model_init_path = "./init_model.txt"  -> Loads the initial global model from a file, num_params is then ignored
  benign_training:
    num_epochs: 5
    batch_size: 32
    optimizer: SGD
    learning_rate: 0.01
crypto:
  enc_type: Plain #l2, Range, Plain
  value_range: 32
  n_partition: 1
  l2_value_range: 32
  check_percentage: 1.0 # 0.0-1.0 for Range i.e., round(num_rangeproofs * check_percentage)
  fp_bits: 32
  fp_frac: 12

dataset:
  dataset: mnist
  data_distribution: IID
job:
  minutes: 240 # Max. minutes to run. Leonhard has 240 and 1440 queues
  cpu_cores: 20
  cpu_mem_per_core: 4096
  use_gpu: 1
  gpu_memory_min: 10240