
- name: Get VPC ID 
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ e2e_base.vpc_name }}"
    region: "{{ e2e_base.aws_region }}"
  register: vpc_result

- name: Extract Vpc id
  set_fact:
    vpc_id: "{{ vpc_result.vpcs[0].vpc_id | default('undefined') }}"
    
- name: Remove All Routes from Security Group
  ec2_group:
    name: "{{ e2e_base.sg_name }}"
    description: "{{ e2e_base.sg_desc }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ e2e_base.aws_region }}"
    purge_rules: true
  when: vpc_id != 'undefined'

# Delete Security Groups
- name: Delete Security Group
  ec2_group:
    name: "{{ e2e_base.sg_name }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ e2e_base.aws_region }}"
    state: absent
  when: vpc_id != 'undefined'
  register: result
  retries: 4
  delay: 5
  until: result is not failed

# Delete Subnet
- name: Delete Server Subnet AZ1
  ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ e2e_base.vpc_subnet_cidr }}"
    region: "{{ e2e_base.aws_region }}"
  when: vpc_id != 'undefined'

# Delete Internet Gateway
- name: Delete Server Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ e2e_base.aws_region }}"
    state: absent
  when: vpc_id != 'undefined'

# Delete VPC
- name: Delete the Server VPC
  ec2_vpc_net:   
    name: "{{ e2e_base.vpc_name }}"
    cidr_block: "{{ e2e_base.vpc_cidr_block }}"
    region: "{{e2e_base.aws_region }}"  
    state: absent  
    purge_cidrs: yes
  register: vpc_delete

- debug: msg="VPC Delete {{ vpc_delete }}"
